### ISSUE TITLE
how does the discregrid handle the holes in mesh?

### ISSUE THREAD

**Issue by Rouen007** [InteractiveComputerGraphics/Discregrid#11]
There always exists some holes in mesh?  
Is there any partical place in the code to handle the issues of holes in meshes?
as far as i am concerned, i noticed that the signed of the distance only related to the nearest entity and related triangle info, in which holes may not handled? 
(UE4 use an heuristic way to determined the "inside", which use the percentage of the hit of mesh faces)

Thank you very much.

**Comment by JoseAntFer** [comment]
There is not special handling for holes in Discregrid.

Discregrid assumes that your mesh is watertight, and therefore it does not have holes. When all the triangles are connected it is possible to discern between inside and outside without heuristics. If a mesh does not fulfill that, you cannot assume that Discregrid will give a particular answer.

**Comment by Rouen007** [comment]
> There is not special handling for holes in Discregrid.
> 
> Discregrid assumes that your mesh is watertight, and therefore it does not have holes. When all the triangles are connected it is possible to discern between inside and outside without heuristics. If a mesh does not fulfill that, you cannot assume that Discregrid will give a particular answer.

Thank you for your reply.
