### ISSUE TITLE
some problem in mesh_distance.cpp

### ISSUE THREAD

**Issue by Rouen007** [InteractiveComputerGraphics/Discregrid#12]
when i peek the source code in geometry/mesh_distance.cpp, i got some questions.
![image](https://user-images.githubusercontent.com/10593332/83405304-d2377980-a43e-11ea-995e-7f23c3b0ca8c.png)
If dmr is lower then 0.0, the code "if (dmr > d_center)" would never be conducted.

And i could figure out the physical meaning of the variables like temp_ and dist_candiate in the piece of code.

Thank you very much.

**Comment by JoseAntFer** [comment]
Thank you for pointing out this issue. The function has been refactored and a comment explaining what it does has been added to the sourcecode.

**Comment by Rouen007** [comment]
Thank you very much.
