### ISSUE TITLE
About time complexity

### ISSUE THREAD

**Issue by heshijiu** [InteractiveComputerGraphics/Discregrid#13]
hi， what's the time complexity of quering a point‘s distance to target object  by using SDF in DiscreGrid,
O(1)  or O(logN)？
If DiscreGrid can find the target cell in O(1), The time complexity shoulbe be O(1),
If DiscreGrid using not regular cell, I think, A tree sturct shoule be used to manager the cells, 
It must find the cell by searching the cell three, and the best time complexity should be O(logN)

which kind of time complexity the DiscreGrid is?

Thank you

**Comment by JoseAntFer** [comment]
Hi,

querying Discregrid has O(1) complexity since it uses a regular grid.

Best regards,
José.
