### ISSUE TITLE
If the mesh is not closed

### ISSUE THREAD

**Issue by FallenCastle** [InteractiveComputerGraphics/Discregrid#15]
Hello,  I want to use Discregrid to generate a signed distance field but my mesh is not closed, is that means I can't use Discregrid to generate a SDF?

**Comment by JoseAntFer** [comment]
Hello,

non closed meshes do not define correct signed distance fields since there is no clear separation between "inside" and "outside". Discregrid is only guaranteed to work with closed meshes. You can use it with open meshes but the results near edges not shared by two triangles is undefined.

Best regards,
José.

**Comment by FallenCastle** [comment]
@JoseAntFer 
Thanks for your reply.

I notice you mentioned that "**You can use it with open meshes but the results near edges not shared by two triangles is undefined**." Is that means when I use it with open meshes I can get a .cdf file and I can get the correct results far away from the edges not shares by two triangles , just the ones near edges not shared by two triangles is incorrect?  If that so, today I use Discregrid to generate a SDF with open meshes and I get a .cdf file, but when I want to load the .cdf file, the  procedure failed.
I don't know what causes the problem.

**Comment by JoseAntFer** [comment]
Hello,

Open meshes are not supported by Discregrid. It produces undefined behaviour, so we do not recommend to use it in that scenario. Also, we cannot provide support for that use case.

That said, I just now used Discregrid to generate a .cdf file of an open surface mesh and I could load it without any problems.

Sorry that we cannot help you further.
Best regards,
José.

**Comment by FallenCastle** [comment]
@JoseAntFer 
Thanks for your reply.
Maybe my mesh file has flaws and I will check it again.

Thanks a lot.

**Comment by JoseAntFer** [comment]
No problem. You are welcome :)
