### ISSUE TITLE
How to decide the resolution?

### ISSUE THREAD

**Issue by FallenCastle** [InteractiveComputerGraphics/Discregrid#16]
Hello,
I wonder what factor determines the resolution ? e.g.  what's the different may cause to the signed distance field when I use resolution{50,50,50} and resolution{100,100,100} ? And how do I decide which resolution I should use?

**Comment by JoseAntFer** [comment]
Hello,

Discregrid uses cubic interpolation inside the cells of a uniform grid. The more cells in the grid, the smaller they are to cover the same volume. The intersection of the target scalar field and a given cell can be typically approximated better the smaller the cell is. Therefore, increasing the resolution from [50, 50, 50] to [100, 100, 100] will give you a better approximation, at the cost of higher building time and memory footprint.

There is not automatic resolution optimization in Discregrid, so you will have to test different resolutions and figure out which works best for you.

Best regards,
José.

**Comment by FallenCastle** [comment]
@JoseAntFer 
Thanks for your reply.

Best regards,
Fallen
