### ISSUE TITLE
If the triangles of the mesh are not consistently oriented.

### ISSUE THREAD

**Issue by FallenCastle** [InteractiveComputerGraphics/Discregrid#18]
Hi,
Recently, I find confused about the situation which if the triangles of the mesh are not all consistently oriented, which means some triangles'  normals point inwards while some point outward. Does the Discregrid be capable of fix the orientation of all triangles, so that they are consistently oriented? 
Best regards,
Fallen.

**Comment by JoseAntFer** [comment]
Hi,

No, Discregrid does not come with such functionality. You can take a look at popular programs to manipulate/fix meshes such as MeshLab or Blender.

Best regards,
José.

**Comment by FallenCastle** [comment]
Thanks for your reply.
Best wishes.
Fallen.

**Comment by FallenCastle** [comment]
> Hi,
> 
> No, Discregrid does not come with such functionality. You can take a look at popular programs to manipulate/fix meshes such as MeshLab or Blender.
> 
> Best regards, José.

Thanks for your reply.
Best wishes.
Fallen.
