### ISSUE TITLE
Can this work fully runs on a gpu？

### ISSUE THREAD

**Issue by lyd405121** [InteractiveComputerGraphics/Discregrid#20]
## Background
- I was implementing a particle based [physic engine](https://github.com/lyd405121/PBD) fully on gpu，here is some result

![taichi](https://user-images.githubusercontent.com/16344694/169471895-772c9518-35f8-40aa-b577-d026134b8425.gif)

- But the collision detect is now my bottle neck，so I want to find some sdf representation on gpu
- I find this repository maybe is the answer, so I read your paper fisrt
- The paper use polymonials and octree to discretize the domain
- To be honest，the paper has too much equation beyond my ability now
- I try to implement it，but I want ask that is it possible to let this code running fully on gpu，because I find a priority queue in the persudo code 

## Another question
- I found nanovdb published
- And openvdb also use a tree-liked data structure（fixed depth），which has some common with this repository
- For your opinion，which one is more easily to implement，nanovdb or Discregrid？

**Comment by JoseAntFer** [comment]
Hello!

Thank you @lyd405121 and @yangfengzzz for your interest in Discregrid. Currently there are no plans to implement our approach on the GPU and sadly, we do not have experience with openvdb or nanovdb so we cannot help there either.

Best regards,
José.
