### ISSUE TITLE
Adding a discrete function 

### ISSUE THREAD

**Issue by GUT2060** [InteractiveComputerGraphics/Discregrid#21]
Hi , 

I have a discrete function that given a point in space will return a numerical value depending on the closest triangle to the mesh. the function is not continuous and might have big jumps between close triangles. 
Using the interpolation when evaluating this function causes erroneous  output. 

what is the correct way to add such a function to the grid and evaluate it afterwards ?

**Comment by JoseAntFer** [comment]
Hello, 

sadly, it is not possible to discretize discontinuous functions with Discregrid. By construction, Discregrid will smoothly interpolate between values at sample points.

As alternative, if performance allows, you can use direct triangle queries to evaluate your exact function. You can take a look at our library to do that: https://github.com/InteractiveComputerGraphics/TriangleMeshDistance

Best regards,
José.
