### ISSUE TITLE
question regarding angular geometries 

### ISSUE THREAD

**Issue by GUT2060** [InteractiveComputerGraphics/Discregrid#25]
Hi,

When using angular geometries consisting of shapes with sharp corners , the discretization seems to generate smoothed and rounded corners. 
Increasing the resolution seems to improve the quality but still clear sharp 90degree corners are smoothed out to a relatively high degree. I'm wondering what exactly are the technical reasons behind this behavior ? and whether there is an alternative to get a cleaner sharper corner discretization ?

Thanks

**Comment by JoseAntFer** [comment]
Hi,

What you describe is a limitation of the approach that Discregrid uses. By construction, Discregrid will interpolate the values of a function within each discretization cell from the values at its perimeter using cubic interpolation.

The point of Discregrid is that it provides very efficient queries to a piece-wise cubic approximation of a function. If you need to obtain the exact values of the function itself, I recommend you evaluate such function directly. If what you need are (signed) distances from a triangle mesh take a look at [TriangleMeshDistance](https://github.com/InteractiveComputerGraphics/TriangleMeshDistance/tree/main).

Best,
José.

**Comment by GUT2060** [comment]
Hi jose,

what about using higher order interpolation schemes or Chebyshev approximations ?

**Comment by JoseAntFer** [comment]
The higher the order the better the approximation, but it still will not be able to represent perfectly sharp features. This also will significantly increase the runtime (both construction and query). Sadly, there are no plans to include other interpolation strategies within Discregrid.

**Comment by GUT2060** [comment]
Thanks for the feedback
