### ISSUE TITLE
How to handle mesh-change situation when using Discregrid

### ISSUE THREAD

**Issue by wghou** [InteractiveComputerGraphics/Discregrid#26]
Hi,

I'm working on a simulation program that contains deformable objects. The Discregrid has been used for collision detection and achieved really good performance.

In the beginning of the simulation process, initial mesh of the deformable object is used to construct a sdf (signed distance field). **But, when the simulaion begins, mesh of the deformable objects would change in some situation, i.e. deleting or subdividing one triangle/tetrahedron from the meshes. I wonder if there is some ways to reconstruct the sdf efficiently, such as reconstructing the sdf in a local area?**

Best regards,

Wenguo Hou

**Comment by JoseAntFer** [comment]
Hello,

Discregrid only supports distance computations to meshes that do not deform.

Best regards,
José.

**Comment by wghou** [comment]
Really appreciate your help. Thanks a lot!

Best regards,

Wenguo Hou
