### ISSUE TITLE
Miniball license conflict

### ISSUE THREAD

**Issue by vijaiaeroastro** [InteractiveComputerGraphics/Discregrid#5]
You have made use of a GPL based mini ball algorithm. This might limit the use of the Discregrid library. There is a more liberal implementation of the same algorithm released under the Apache license here (https://github.com/hbf/miniball/tree/master/cpp/main). This might allow more liberal use of the library.

**Comment by Kugelstadt** [comment]
Hi. Thanks for pointing that out. We replaced miniball with an own implementation, such that Discregrid can be used under the MIT license.
